spring.application.name=body-composition-api-demo
# データはtestdbに保存
spring.datasource.url=jdbc:h2:mem:testdb
# ドライバーでJava とデータベースを通信させる
spring.datasource.driverClassName=org.h2.Driver
# データベースへログインするための「ユーザー名」，System Administrator（システム管理者）の略
spring.datasource.username=sa
# 「パスワードなし」で接続する
spring.datasource.password=

# Java の @Entity クラスをもとに、DBのテーブルを自動生成・更新するモードを指定
spring.jpa.hibernate.ddl-auto=update
# バックグラウンドで実行された SQL 文をコンソール（ログ）に出力するかどうかを指定
spring.jpa.show-sql=true